### ISSUE TITLE
Create gradle plugin for avd management

### ISSUE THREAD

**Issue by kzaikin** [Grigory-Rylov/AndroidEmulatorManager#2]

**Comment by Grigory-Rylov** [comment]
added EmulatorManagerPlugin with tasks:
createEmulators, startEmulators, stopRunningEmulators, deleteEmulators
usage in https://github.com/Grigory-Rylov/AndroidEmulatorManager/blob/master/src/test/integration/java/com/github/grishberg/androidemulatormanager/EmulatorManagerPluginIntegrationTest.java
